/**
 * Guía de Mallorca del panel de cliente.
 *
 * Lugares: selección del equipo (lista "Utopia Van Life" de Google Maps) + imprescindibles.
 * Coordenadas comprobadas en OpenStreetMap / Wikipedia (octubre 2026).
 * Fotos de Wikimedia Commons con su autor y licencia (se muestran como crédito).
 * Normativa revisada en octubre 2026: repasar cada temporada (Formentor cambia de fechas cada año).
 */

export type SpotCategory = 'calas' | 'miradores' | 'naturaleza' | 'pueblos' | 'dormir'

export type TagKey =
  | 'parking-free' | 'parking-paid' | 'walk' | 'no-services' | 'services'
  | 'sunset' | 'sunrise' | 'restricted' | 'mountain-road' | 'narrow'
  | 'water' | 'dump' | 'power' | 'swim' | 'hike' | 'history' | 'quiet' | 'food' | 'family'

/** Una etiqueta puede llevar un texto propio (p. ej. "15 min a pie") */
export type SpotTag = TagKey | { key: TagKey; label: string }

export interface GuideSpot {
  id: string
  name: string
  category: SpotCategory
  area: string
  lat: number
  lng: number
  /** Qué es y por qué merece la pena */
  summary: string
  /** Cómo llegar y aparcar con la camper */
  camperTip: string
  /** Recomendación de la casa: cuándo ir, qué hacer, el truco que solo sabe quien ha estado */
  utopiaTip: string
  /** Aviso importante (restricciones, accesos), si lo hay */
  warning?: string
  /** Aparcamiento recomendado si no se puede llegar con la camper al lugar */
  parking?: { lat: number; lng: number }
  tags: SpotTag[]
  /** Sin foto, la ficha muestra una portada con el color de la categoría */
  image?: string
  credit?: { author: string; license: string; source: string }
}

export const CATEGORY_LABELS: Record<SpotCategory, string> = {
  calas: 'Calas y playas',
  miradores: 'Miradores',
  naturaleza: 'Naturaleza e historia',
  pueblos: 'Pueblos',
  dormir: 'Dormir y servicios',
}

/** Colores vivos de la marca para el mapa y las etiquetas (legibles en claro y oscuro) */
export const CATEGORY_COLORS: Record<SpotCategory, string> = {
  calas: '#0E8AC4',
  miradores: '#E08A12',
  naturaleza: '#2F9E5B',
  pueblos: '#D9573B',
  dormir: '#7356D6',
}

export const TAG_META: Record<TagKey, { label: string; tone: 'sky' | 'amber' | 'sage' | 'rose' | 'gold' | 'violet' | 'neutral' }> = {
  'parking-free': { label: 'Parking gratis', tone: 'sage' },
  'parking-paid': { label: 'Parking de pago', tone: 'neutral' },
  walk: { label: 'Llega a pie', tone: 'sky' },
  'no-services': { label: 'Sin servicios', tone: 'neutral' },
  services: { label: 'Servicios', tone: 'sage' },
  sunset: { label: 'Atardecer', tone: 'amber' },
  sunrise: { label: 'Amanecer', tone: 'amber' },
  restricted: { label: 'Acceso restringido', tone: 'rose' },
  'mountain-road': { label: 'Carretera de montaña', tone: 'rose' },
  narrow: { label: 'Calles estrechas', tone: 'rose' },
  water: { label: 'Agua potable', tone: 'sky' },
  dump: { label: 'Vaciado', tone: 'violet' },
  power: { label: 'Electricidad', tone: 'gold' },
  swim: { label: 'Baño', tone: 'sky' },
  hike: { label: 'Senderismo', tone: 'sage' },
  history: { label: 'Historia', tone: 'gold' },
  quiet: { label: 'Tranquilo', tone: 'sage' },
  food: { label: 'Para comer', tone: 'amber' },
  family: { label: 'Familiar', tone: 'sky' },
}

const commons = (file: string) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file.replace(/ /g, '_'))}`

const FORMENTOR_WARNING = 'Del 15 de mayo al 18 de octubre de 2026 no se puede circular en vehículo privado por la carretera de Formentor (Ma-2210) de 10:00 a 22:00.'

export const GUIDE_SPOTS: GuideSpot[] = [
  // ── Calas y playas ──
  {
    id: 'calo-des-moro',
    name: 'Caló des Moro',
    category: 'calas',
    area: 'Santanyí',
    lat: 39.3137, lng: 3.1216,
    summary: 'Una de las calas más fotografiadas de la isla: agua turquesa entre paredes de roca y pinos. Es pequeña y en verano se llena muy pronto.',
    camperTip: 'Deja la camper en el aparcamiento gratuito de s’Almunia y Cala Llombards y camina unos 20 minutos. Cerca de la cala no se puede aparcar y se multa.',
    utopiaTip: 'Ve a primera hora o a última de la tarde: tendrás el agua casi para ti. De camino, asómate a Cala s’Almunia y sus casetas de pescadores.',
    parking: { lat: 39.3206, lng: 3.1265 },
    tags: ['parking-free', { key: 'walk', label: '20 min a pie' }, 'no-services', 'swim'],
    image: '/images/guia/calo-des-moro.jpg',
    credit: { author: 'Tommie Hansen', license: 'CC BY 2.0', source: commons('View of the bay at Calo des Moro, Mallorca (Spain) (23899506181).jpg') },
  },
  {
    id: 'cala-llombards',
    name: 'Cala Llombards',
    category: 'calas',
    area: 'Santanyí',
    lat: 39.3238, lng: 3.1389,
    summary: 'Cala de arena blanca con casetas de pescadores y agua tranquila, más amplia y familiar que su vecina Caló des Moro.',
    camperTip: 'Hay un aparcamiento junto a la cala (calle del Foscant), pequeño. Si está lleno, usa el grande de s’Almunia y Cala Llombards.',
    utopiaTip: 'Perfecta para pasar el día con niños: entra poco a poco en el agua y hay sombra de pinos en los laterales.',
    parking: { lat: 39.3234, lng: 3.1379 },
    tags: ['parking-free', 'family', 'swim'],
    image: '/images/guia/cala-llombards.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Cala Llombards 04.jpg') },
  },
  {
    id: 'cala-mondrago',
    name: 'Cala Mondragó',
    category: 'calas',
    area: 'Parc Natural de Mondragó, Santanyí',
    lat: 39.3522, lng: 3.1883,
    summary: 'Dos playas dentro de un parque natural, rodeadas de pinar, unidas por un camino junto al mar.',
    camperTip: 'Hay dos aparcamientos de pago: S’Amarador y Ses Fonts de n’Alis. En temporada alta llega antes de las 10.',
    utopiaTip: 'Sigue el sendero señalizado entre S’Amarador y Mondragó: en diez minutos tienes vistas de las dos calas desde arriba.',
    parking: { lat: 39.3456, lng: 3.1869 },
    tags: ['parking-paid', 'services', 'family', 'hike'],
    image: '/images/guia/cala-mondrago.jpg',
    credit: { author: 'Kawamondrago', license: 'CC BY-SA 3.0', source: commons('Mondragó in 4.JPG') },
  },
  {
    id: 'es-trenc',
    name: 'Es Trenc',
    category: 'calas',
    area: 'Campos',
    lat: 39.3405, lng: 2.9951,
    summary: 'Varios kilómetros de arena fina y dunas sin edificios. La playa larga más natural de Mallorca.',
    camperTip: 'Aparca en los aparcamientos de pago señalizados. Las dunas están protegidas: no se puede pisar ni aparcar fuera de las zonas marcadas.',
    utopiaTip: 'Camina hacia el sur, lejos de los accesos: cuanto más te alejas, más tranquila está la playa.',
    tags: ['parking-paid', 'swim', 'family'],
    image: '/images/guia/es-trenc.jpg',
    credit: { author: 'Yaroslav Syubayev', license: 'CC BY-SA 4.0', source: commons('Es Trenc Winter.jpg') },
  },
  {
    id: 'cala-varques',
    name: 'Cala Varques',
    category: 'calas',
    area: 'Manacor',
    lat: 39.4999, lng: 3.2960,
    summary: 'Cala virgen sin edificios ni servicios, con cuevas y un arco de roca natural en los acantilados cercanos.',
    camperTip: 'No hay carretera hasta la cala. Se aparca junto a la carretera de acceso y se sigue un camino de tierra de unos 20 minutos.',
    utopiaTip: 'Lleva gafas de snorkel y agua de sobra: no hay chiringuito y las rocas de los lados están llenas de vida.',
    tags: [{ key: 'walk', label: '20 min a pie' }, 'no-services', 'swim'],
    image: '/images/guia/cala-varques.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Cala Varques 29.jpg') },
  },
  {
    id: 'portocolom',
    name: 'Portocolom: s’Arenal y el faro',
    category: 'calas',
    area: 'Felanitx',
    lat: 39.4200, lng: 3.2748,
    summary: 'Pueblo marinero con una de las bahías naturales más grandes de la isla. Junto al faro están las playas de s’Arenal Gran y s’Arenal Petit.',
    camperTip: 'Hay un aparcamiento amplio en la carretera del faro, a pocos minutos andando de las playas.',
    utopiaTip: 'Termina el día paseando hasta el faro de Punta de ses Crestes: el atardecer sobre la bahía es de los mejores del Llevant.',
    parking: { lat: 39.4231, lng: 3.2685 },
    tags: ['parking-free', 'swim', 'sunset', 'services'],
    image: '/images/guia/far-portocolom.jpg',
    credit: { author: 'Lopezsuarez', license: 'CC BY-SA 4.0', source: commons('Faro de Porto Colom, en Felanich (España).jpg') },
  },
  {
    id: 'cala-agulla',
    name: 'Cala Agulla y Cala Lliteres',
    category: 'calas',
    area: 'Capdepera',
    lat: 39.7227, lng: 3.4522,
    summary: 'Playa amplia de arena con dunas y pinar junto a Cala Rajada. Desde aquí sale un sendero a calas más escondidas.',
    camperTip: 'Aparcamiento grande de pago junto a la playa, cómodo para campers.',
    utopiaTip: 'Desde el extremo norte de la playa, el camino por el pinar te lleva a Cala Moltó en unos 20 minutos, mucho más tranquila.',
    parking: { lat: 39.7204, lng: 3.4558 },
    tags: ['parking-paid', 'services', 'family', 'hike'],
    image: '/images/guia/cala-agulla.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Cala Agulla 01.jpg') },
  },
  {
    id: 'cala-mesquida',
    name: 'Cala Mesquida',
    category: 'calas',
    area: 'Capdepera',
    lat: 39.7444, lng: 3.4339,
    summary: 'Playa abierta de arena dorada y dunas, con un sistema dunar protegido detrás. Suele haber algo de oleaje.',
    camperTip: 'Hay un aparcamiento a la entrada de la playa. En agosto se llena pronto.',
    utopiaTip: 'Si sopla tramontana, el mar se pone bravo aquí: ese día mejor elige Cala Agulla o Cala Torta.',
    parking: { lat: 39.7456, lng: 3.4306 },
    tags: ['parking-free', 'swim', 'services'],
    image: '/images/guia/cala-mesquida.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Cala Mesquida 03.jpg') },
  },
  {
    id: 'cala-torta',
    name: 'Cala Torta y Cala Mitjana',
    category: 'calas',
    area: 'Artà',
    lat: 39.7498, lng: 3.4173,
    summary: 'Dos calas vírgenes de arena en la costa salvaje de Artà, sin construcciones a la vista.',
    camperTip: 'El último tramo es una pista de tierra estrecha y con baches. Aparca en el mirador junto a la finca de Sa Duaia y baja andando.',
    utopiaTip: 'Es de los pocos sitios de la isla que siguen igual que hace cuarenta años. Llévate comida y agua y quédate a ver caer la tarde.',
    parking: { lat: 39.7296, lng: 3.3888 },
    tags: ['walk', 'no-services', 'quiet', 'swim'],
    image: '/images/guia/cala-torta.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Cala Torta 07.jpg') },
  },
  {
    id: 'cala-sant-vicenc',
    name: 'Cala Sant Vicenç',
    category: 'calas',
    area: 'Pollença',
    lat: 39.9208, lng: 3.0560,
    summary: 'Pequeño pueblo con cuatro calas de agua transparente a los pies de los acantilados del Cavall Bernat.',
    camperTip: 'Usa el aparcamiento gratuito de la avenida del Cavall Bernat, a la entrada, y baja andando.',
    utopiaTip: 'Cala Molins y Cala Barques tienen el agua más clara. Por la tarde, el sol se pone justo sobre el Cavall Bernat.',
    parking: { lat: 39.9202, lng: 3.0536 },
    tags: ['parking-free', 'services', 'swim', 'sunset'],
    image: '/images/guia/cala-sant-vicenc.jpg',
    credit: { author: 'Silar', license: 'CC BY-SA 4.0', source: commons('02017 0139 Cala Sant Vicenç, Majorca.jpg') },
  },
  {
    id: 'platja-formentor',
    name: 'Platja de Formentor',
    category: 'calas',
    area: 'Pollença',
    lat: 39.9270, lng: 3.1422,
    summary: 'Playa de agua muy clara bajo un pinar, en la península de Formentor.',
    camperTip: 'Fuera del horario restringido se llega por la Ma-2210 y hay aparcamiento de pago junto a la playa. En temporada, entra antes de las 10.',
    utopiaTip: 'Llega a las 9: tendrás sitio para aparcar, la playa en calma y podrás subir a los miradores antes de que cierren la carretera.',
    warning: FORMENTOR_WARNING,
    parking: { lat: 39.9301, lng: 3.1345 },
    tags: ['restricted', 'parking-paid', 'swim'],
    image: '/images/guia/platja-formentor.jpg',
    credit: { author: 'HejaSverige!', license: 'CC BY-SA 3.0', source: commons('Platja de Formentor.JPG') },
  },
  {
    id: 'cala-tuent',
    name: 'Cala Tuent',
    category: 'calas',
    area: 'Escorca',
    lat: 39.8401, lng: 2.7760,
    summary: 'Cala tranquila de canto rodado y arena en plena Serra de Tramuntana, con el Puig Major de fondo.',
    camperTip: 'Se llega por un desvío de la carretera de Sa Calobra: estrecho y con muchas curvas. Ve sin prisa y con el depósito lleno.',
    utopiaTip: 'Es la alternativa tranquila a Sa Calobra. Para en la iglesia de Sant Llorenç al bajar: la vista de la cala desde arriba es espectacular.',
    tags: ['mountain-road', 'quiet', 'swim'],
    image: '/images/guia/cala-tuent.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Cala Tuent 13.JPG') },
  },
  {
    id: 'portals-vells',
    name: 'Portals Vells',
    category: 'calas',
    area: 'Calvià',
    lat: 39.4723, lng: 2.5202,
    summary: 'Cala resguardada entre pinos con una antigua cueva-cantera excavada en la roca, a media hora de Palma.',
    camperTip: 'Hay aparcamiento junto a la cala, pequeño y que se llena en verano. Llega temprano.',
    utopiaTip: 'Ideal para el primer o el último día del viaje: está cerca de nuestra base y del aeropuerto.',
    tags: ['swim', 'family'],
    image: '/images/guia/portals-vells.jpg',
    credit: { author: 'Autor desconocido', license: 'CC BY-SA 3.0', source: commons('Portals vells 01.jpg') },
  },
  {
    id: 'cala-blanca-andratx',
    name: 'Cala Blanca',
    category: 'calas',
    area: 'Andratx',
    lat: 39.5376, lng: 2.4057,
    summary: 'Pequeña cala de piedras y agua cristalina entre Camp de Mar y el Port d’Andratx, sin construcciones.',
    camperTip: 'El acceso es por el camí de Cala Blanca, estrecho. Aparca donde esté permitido antes de llegar y termina a pie.',
    utopiaTip: 'Llévate escarpines y gafas de snorkel: el fondo de roca es precioso y apenas hay gente fuera de agosto.',
    tags: ['walk', 'no-services', 'swim', 'quiet'],
  },

  // ── Miradores ──
  {
    id: 'mirador-colomer',
    name: 'Mirador d’es Colomer',
    category: 'miradores',
    area: 'Formentor, Pollença',
    lat: 39.9310, lng: 3.1124,
    summary: 'La vista clásica de los acantilados de Formentor y el islote del Colomer.',
    camperTip: 'El aparcamiento es pequeño. En temporada, ve antes de las 10 o sube en el bus que sale del Port de Pollença.',
    utopiaTip: 'Ven al amanecer: el sol sale por detrás de la península y la luz sobre los acantilados es increíble.',
    warning: FORMENTOR_WARNING,
    tags: ['restricted', 'sunrise'],
    image: '/images/guia/mirador-colomer.jpg',
    credit: { author: 'pjt56', license: 'CC BY-SA 3.0', source: commons('CapFormentor-pjt2.jpg') },
  },
  {
    id: 'talaia-albercutx',
    name: 'Talaia d’Albercutx',
    category: 'miradores',
    area: 'Formentor, Pollença',
    lat: 39.9288, lng: 3.1171,
    summary: 'Antigua torre de vigía en lo alto de Formentor, con vista de 360° sobre las bahías de Pollença y Alcúdia.',
    camperTip: 'La pista de subida desde el mirador d’es Colomer es estrecha y empinada. Sube andando desde el mirador.',
    utopiaTip: 'Es el mismo paseo que el Colomer, pero con la mitad de gente y el doble de vistas.',
    warning: FORMENTOR_WARNING,
    tags: ['restricted', 'hike', 'sunrise'],
    image: '/images/guia/talaia-albercutx.jpg',
    credit: { author: 'Frank Vincentz', license: 'CC BY-SA 3.0', source: commons("Pollença - Ma-10 - Talaia d'Albercutx 01 ies.jpg") },
  },
  {
    id: 'raco-en-tomas',
    name: 'Mirador hacia el Cap de Formentor',
    category: 'miradores',
    area: 'Formentor, Pollença',
    lat: 39.9546, lng: 3.1898,
    summary: 'Parada en la carretera del faro con la vista de la punta de Formentor y sus acantilados cayendo al mar.',
    camperTip: 'Es un apartadero en la Ma-2210: para solo si hay hueco y sin bloquear la carretera.',
    utopiaTip: 'Mejor que el propio faro, que está siempre lleno: desde aquí ves la península entera.',
    warning: FORMENTOR_WARNING,
    tags: ['restricted', 'sunrise'],
  },
  {
    id: 'sa-foradada',
    name: 'Sa Foradada (Son Marroig)',
    category: 'miradores',
    area: 'Deià',
    lat: 39.7511, lng: 2.6290,
    summary: 'La roca agujereada que entra en el mar, vista desde la finca del Archiduque Luis Salvador.',
    camperTip: 'Aparca en el apartadero de la Ma-10 junto a Son Marroig. No bajes con la camper por el camino hacia la península.',
    utopiaTip: 'Uno de los mejores atardeceres de la isla: llega media hora antes de que se ponga el sol.',
    parking: { lat: 39.7511, lng: 2.6300 },
    tags: ['sunset', 'history'],
    image: '/images/guia/sa-foradada.jpg',
    credit: { author: 'Antoni Sureda', license: 'CC BY-SA 3.0', source: commons('NaForadada.jpg') },
  },
  {
    id: 'mirador-ses-animes',
    name: 'Mirador de ses Ànimes',
    category: 'miradores',
    area: 'Banyalbufar',
    lat: 39.6837, lng: 2.5000,
    summary: 'La Torre del Verger, una atalaya del siglo XVI colgada sobre el mar, con vistas a toda la costa de Tramuntana.',
    camperTip: 'Está junto a la Ma-10 entre Banyalbufar y Estellencs, con un pequeño aparcamiento al lado.',
    utopiaTip: 'Sube a lo alto de la torre por la escalera de piedra: la foto de la costa desde arriba es la mejor de la Ma-10.',
    parking: { lat: 39.6827, lng: 2.5001 },
    tags: ['sunset', 'history'],
    image: '/images/guia/mirador-ses-animes.jpg',
    credit: { author: 'Antonio De Lorenzo', license: 'CC BY 2.5', source: commons('Torre Verger Banyalbufar 4.JPG') },
  },
  {
    id: 'mirador-ricardo-roca',
    name: 'Mirador de Ricardo Roca (Es Grau)',
    category: 'miradores',
    area: 'Estellencs',
    lat: 39.6235, lng: 2.4239,
    summary: 'Mirador de 1919 sobre los acantilados de la costa oeste, en la Ma-10 al sur de Estellencs.',
    camperTip: 'Aparcamiento junto a la carretera. Las curvas de la Ma-10 en este tramo son cerradas: conduce despacio.',
    utopiaTip: 'Combínalo con el Coll de sa Gramola en la misma tarde: dos atardeceres distintos en veinte minutos de carretera.',
    tags: ['sunset', 'mountain-road'],
  },
  {
    id: 'coll-sa-gramola',
    name: 'Coll de sa Gramola',
    category: 'miradores',
    area: 'Andratx',
    lat: 39.6069, lng: 2.4095,
    summary: 'Collado de la Ma-10 sobre Andratx, con mirador hacia el mar y zona de picnic entre pinos.',
    camperTip: 'Tiene aparcamiento a pie de carretera, cómodo para hacer una parada.',
    utopiaTip: 'Buen sitio para comer algo a la sombra antes de empezar la Ma-10 hacia el norte.',
    tags: ['parking-free', 'sunset', 'food'],
  },
  {
    id: 'nus-corbata',
    name: 'Nus de sa Corbata',
    category: 'miradores',
    area: 'Escorca',
    lat: 39.8320, lng: 2.8160,
    summary: 'El famoso “nudo de corbata” de la carretera de Sa Calobra, donde la calzada pasa por debajo de sí misma.',
    camperTip: 'Hay poco espacio para parar. Hazlo solo si hay sitio en el apartadero y vigila el tráfico de bajada.',
    utopiaTip: 'Haz la foto desde arriba al bajar y vuelve a mirarlo en la subida: la perspectiva cambia por completo.',
    tags: ['mountain-road'],
    image: '/images/guia/nus-corbata.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Nus de sa Corbata 01.jpg') },
  },

  // ── Naturaleza e historia ──
  {
    id: 'sa-calobra',
    name: 'Sa Calobra y Torrent de Pareis',
    category: 'naturaleza',
    area: 'Escorca',
    lat: 39.8522, lng: 2.8058,
    summary: 'La desembocadura del Torrent de Pareis entre paredes de roca de cientos de metros, al final de una de las carreteras más espectaculares de Europa.',
    camperTip: 'La Ma-2141 tiene curvas muy cerradas y mucho tráfico de autobuses y ciclistas. Baja a primera hora y aparca en el parking de pago del final.',
    utopiaTip: 'Al bajar, para a desayunar en la zona del aparcamiento antes de que lleguen los barcos. Luego cruza los túneles a pie hasta el torrente.',
    warning: 'Carretera exigente: solo si te sientes cómodo conduciendo la camper en curvas de montaña.',
    parking: { lat: 39.8487, lng: 2.7990 },
    tags: ['mountain-road', 'parking-paid', 'hike', 'food'],
    image: '/images/guia/sa-calobra.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Torrent de Pareis 07a.jpg') },
  },
  {
    id: 'sant-llorenc-escorca',
    name: 'Sant Llorenç d’Escorca',
    category: 'naturaleza',
    area: 'Escorca',
    lat: 39.8424, lng: 2.7876,
    summary: 'Pequeña iglesia del siglo XIII en el collado donde la carretera empieza a bajar hacia Cala Tuent, con vistas sobre la cala.',
    camperTip: 'Está en el desvío a Cala Tuent. Aparca junto a la iglesia sin bloquear el paso.',
    utopiaTip: 'De nuestros sitios favoritos para comer con vistas: tranquilo, a la sombra y con el mar abajo.',
    tags: ['food', 'quiet', 'history'],
  },
  {
    id: 'far-ses-salines',
    name: 'Far de ses Salines',
    category: 'naturaleza',
    area: 'Ses Salines',
    lat: 39.2652, lng: 3.0534,
    summary: 'El extremo sur de Mallorca. Desde el faro sale un paseo junto al mar hasta playas vírgenes de arena blanca.',
    camperTip: 'Hay poco sitio para aparcar junto al faro; si está lleno, deja la camper algo antes, en un lugar permitido.',
    utopiaTip: 'Sigue la costa hacia el oeste, unos 30 minutos a pie, hasta Es Caragol: una playa salvaje que poca gente conoce.',
    tags: ['hike', 'no-services', 'sunset'],
    image: '/images/guia/far-ses-salines.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY-SA 3.0', source: commons('Far des Cap Salines 02.jpg') },
  },
  {
    id: 'torre-cala-pi',
    name: 'Torre de Cala Pi',
    category: 'naturaleza',
    area: 'Llucmajor',
    lat: 39.3615, lng: 2.8353,
    summary: 'Torre de vigía de 1543 sobre la entrada de Cala Pi, una cala estrecha y profunda entre acantilados.',
    camperTip: 'Aparca en la urbanización, en zona permitida. A la cala se baja por unas escaleras desde la parte alta.',
    utopiaTip: 'Sube a la torre para ver la cala desde arriba y después baja a bañarte: el agua es muy tranquila.',
    tags: ['history', 'swim'],
    image: '/images/guia/torre-cala-pi.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Torre de Cala Pi 02.jpg') },
  },
  {
    id: 'pedreres-puig-de-ros',
    name: 'Pedreres de la Seu y Cala Vella',
    category: 'naturaleza',
    area: 'Llucmajor',
    lat: 39.4505, lng: 2.7444,
    summary: 'Antiguas canteras de marès junto al mar en Puig de Ros, punto de partida de un paseo costero hasta Cala Vella.',
    camperTip: 'Hay un aparcamiento cerca de las canteras, en la urbanización de Puig de Ros.',
    utopiaTip: 'Plan tranquilo a 20 minutos de nuestra base: perfecto para el día de llegada.',
    tags: ['parking-free', 'hike', 'quiet'],
  },
  {
    id: 'coves-arta',
    name: 'Coves d’Artà',
    category: 'naturaleza',
    area: 'Capdepera',
    lat: 39.6561, lng: 3.4510,
    summary: 'Cuevas enormes abiertas sobre el mar en el Cap Vermell, con salas de estalactitas de varios pisos de altura.',
    camperTip: 'Aparcamiento gratuito a la entrada. Las visitas son guiadas y con horario.',
    utopiaTip: 'Buen plan para un día de viento o lluvia. Al salir, la vista de la bahía de Canyamel desde la boca de la cueva merece la pena.',
    parking: { lat: 39.6567, lng: 3.4485 },
    tags: ['parking-free', 'history', 'family'],
    image: '/images/guia/coves-arta.jpg',
    credit: { author: 'H. Zell', license: 'CC BY-SA 3.0', source: commons('Coves d’Artà - El elefante.jpg') },
  },
  {
    id: 'serral-falcons',
    name: 'Torre del Serral dels Falcons',
    category: 'naturaleza',
    area: 'Porto Cristo, Manacor',
    lat: 39.5333, lng: 3.3370,
    summary: 'Torre de defensa del siglo XVI sobre los acantilados de Porto Cristo, con vistas a la costa del Llevant.',
    camperTip: 'Está al final de una calle residencial; aparca en la plaza cercana sin molestar a los vecinos.',
    utopiaTip: 'Ven al atardecer: la piedra de la torre se vuelve dorada y apenas hay nadie.',
    tags: ['history', 'sunset', 'quiet'],
    image: '/images/guia/serral-falcons.jpg',
    credit: { author: 'Kritzolina', license: 'CC BY-SA 4.0', source: commons('Evening light at Torre del Serral dels Falcons 03.jpg') },
  },
  {
    id: 'ermita-victoria',
    name: 'La Victòria',
    category: 'naturaleza',
    area: 'Alcúdia',
    lat: 39.8732, lng: 3.1704,
    summary: 'Ermita del siglo XVII en la península de la Victòria, rodeada de pinar y con senderos hacia la Talaia d’Alcúdia y pequeñas calas.',
    camperTip: 'Aparcamiento público junto a la ermita. La carretera de acceso es estrecha pero asfaltada.',
    utopiaTip: 'Baja por el Camí Vell de la Victòria a las calitas de roca: agua transparente y casi nadie, incluso en verano.',
    tags: ['parking-free', 'hike', 'quiet', 'food'],
    image: '/images/guia/ermita-victoria.jpg',
    credit: { author: 'Kritzolina', license: 'CC BY-SA 4.0', source: commons('Ermita de la Victoria 01.jpg') },
  },
  {
    id: 'planicia',
    name: 'Finca pública de Planícia',
    category: 'naturaleza',
    area: 'Banyalbufar',
    lat: 39.6726, lng: 2.4945,
    summary: 'Finca pública de la Serra de Tramuntana con senderos entre encinares y bancales con vistas al mar.',
    camperTip: 'Aparcamiento a pie de la Ma-10, al inicio del camino.',
    utopiaTip: 'Haz el paseo por la mañana y termina comiendo en Banyalbufar, a diez minutos.',
    tags: ['hike', 'quiet', 'parking-free'],
    image: '/images/guia/planicia.jpg',
    credit: { author: 'Teresa Rocamora', license: 'CC BY-SA 3.0 es', source: commons('Planicia.jpg') },
  },

  // ── Pueblos ──
  {
    id: 'valldemossa',
    name: 'Valldemossa',
    category: 'pueblos',
    area: 'Serra de Tramuntana',
    lat: 39.7117, lng: 2.6226,
    summary: 'Pueblo de piedra y calles con flores, famoso por la Cartuja donde vivieron Chopin y George Sand.',
    camperTip: 'No entres en el casco antiguo. Usa los aparcamientos de pago de la entrada del pueblo.',
    utopiaTip: 'Pide una coca de patata en cualquier horno del pueblo: es la especialidad local.',
    tags: ['parking-paid', 'narrow', 'history', 'food'],
    image: '/images/guia/valldemossa.jpg',
    credit: { author: 'Abrget47j', license: 'CC BY-SA 3.0', source: commons('Valdemosa, en Baleares (España).jpg') },
  },
  {
    id: 'deia',
    name: 'Deià',
    category: 'pueblos',
    area: 'Serra de Tramuntana',
    lat: 39.7500, lng: 2.6331,
    summary: 'Casas de piedra escalonadas sobre una colina frente al mar. Aquí vivió el escritor Robert Graves.',
    camperTip: 'Aparcar es muy complicado. Si no encuentras sitio en la entrada, verlo desde la carretera y seguir es mejor plan.',
    utopiaTip: 'Sube a la iglesia por las escaleras del pueblo: desde el pequeño cementerio se ve todo el valle hasta el mar.',
    tags: ['narrow', 'history'],
    image: '/images/guia/deia.jpg',
    credit: { author: 'Fr. Diana Korn', license: 'CC BY-SA 4.0', source: commons('Deyá, en Baleares (España).jpg') },
  },
  {
    id: 'fornalutx',
    name: 'Fornalutx',
    category: 'pueblos',
    area: 'Serra de Tramuntana',
    lat: 39.7827, lng: 2.7409,
    summary: 'Pequeño pueblo de montaña entre naranjos, considerado uno de los más bonitos de España.',
    camperTip: 'Las calles son muy estrechas y empinadas. Usa el aparcamiento de la Ma-10 y baja andando.',
    utopiaTip: 'Pierde el rato por las escaleras del centro y tómate un zumo de naranja de los huertos del valle.',
    parking: { lat: 39.7907, lng: 2.7254 },
    tags: ['narrow', 'walk', 'quiet'],
    image: '/images/guia/fornalutx.jpg',
    credit: { author: 'Paucabot', license: 'CC BY-SA 3.0', source: commons('Fornalutx-cropped.jpeg') },
  },
  {
    id: 'port-soller',
    name: 'Port de Sóller',
    category: 'pueblos',
    area: 'Sóller',
    lat: 39.7986, lng: 2.6936,
    summary: 'Bahía redonda rodeada de montañas, con paseo marítimo y el tranvía de madera que sube a Sóller.',
    camperTip: 'Hay aparcamientos grandes a la entrada del puerto. Deja la camper ahí y muévete a pie o en tranvía.',
    utopiaTip: 'Al atardecer, sube andando al faro del Cap Gros: las vistas de la bahía con las montañas detrás son preciosas.',
    tags: ['services', 'sunset', 'family'],
    image: '/images/guia/port-soller.jpg',
    credit: { author: 'BuzzWoof', license: 'Dominio público', source: commons('Port de Sóller.JPG') },
  },
  {
    id: 'santuari-lluc',
    name: 'Santuari de Lluc',
    category: 'pueblos',
    area: 'Escorca',
    lat: 39.8229, lng: 2.8844,
    summary: 'Monasterio en el corazón de la Serra de Tramuntana, punto de partida de excursiones y casa de la Escolania dels Blauets.',
    camperTip: 'Tiene aparcamiento de pago amplio. La carretera de subida (Ma-10) es de montaña: conduce con calma.',
    utopiaTip: 'Sube el Camí dels Misteris hasta el monumento de la cima: 15 minutos y una vista de toda la sierra.',
    tags: ['parking-paid', 'mountain-road', 'hike', 'history'],
    image: '/images/guia/santuari-lluc.jpg',
    credit: { author: 'H. Zell', license: 'CC BY-SA 3.0', source: commons('Santuari de Lluc - View from Monte del Rosario.jpg') },
  },
  {
    id: 'arta',
    name: 'Artà',
    category: 'pueblos',
    area: 'Llevant',
    lat: 39.6952, lng: 3.3512,
    summary: 'Pueblo señorial coronado por el santuario amurallado de Sant Salvador, con vistas a toda la bahía.',
    camperTip: 'Aparca en las afueras y sube andando por las escaleras hasta Sant Salvador.',
    utopiaTip: 'Recorre el camino de ronda de la muralla de Sant Salvador: se ve el Llevant entero hasta el mar.',
    tags: ['narrow', 'history'],
    image: '/images/guia/arta.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Artá, en Baleares (España).jpg') },
  },
  {
    id: 'alcudia',
    name: 'Alcúdia',
    category: 'pueblos',
    area: 'Norte',
    lat: 39.8525, lng: 3.1192,
    summary: 'Ciudad amurallada medieval junto a las ruinas de Pollentia, la ciudad romana más importante de la isla.',
    camperTip: 'Aparca fuera de las murallas; el casco antiguo es peatonal en gran parte.',
    utopiaTip: 'Pasea por encima de la muralla y termina en las ruinas romanas de Pollentia, a cinco minutos andando.',
    tags: ['history', 'family'],
    image: '/images/guia/alcudia.jpg',
    credit: { author: 'Antonio De Lorenzo', license: 'CC BY 2.5', source: commons('Alcudia, en Mallorca (Baleares, España).jpg') },
  },
  {
    id: 'catedral-palma',
    name: 'Palma y la Catedral',
    category: 'pueblos',
    area: 'Palma',
    lat: 39.5675, lng: 2.6481,
    summary: 'La Seu, la catedral gótica frente al mar, y el casco antiguo de Palma para un día de paseo.',
    camperTip: 'Los parkings subterráneos del centro suelen tener límite de altura. Usa un aparcamiento en superficie y entra a pie.',
    utopiaTip: 'Ve a primera hora para evitar las colas y después baja a pasear por el Parc de la Mar, frente a la fachada.',
    warning: 'Revisa la altura de la camper antes de entrar en cualquier parking cubierto.',
    parking: { lat: 39.5622, lng: 2.6636 },
    tags: ['history', 'food', 'family'],
    image: '/images/guia/catedral-palma.jpg',
    credit: { author: 'Javier Pérez Montes', license: 'CC BY-SA 4.0', source: commons('Catedral de Palma de Mallorca 01.jpg') },
  },

  // ── Dormir y servicios ──
  {
    id: 'area-son-serra',
    name: 'Área camper de Son Serra de Marina',
    category: 'dormir',
    area: 'Santa Margalida',
    lat: 39.7353, lng: 3.2258,
    summary: 'La primera área equipada para campers de Mallorca, a unos 200 m de la playa. Puedes dormir con todas las de la ley.',
    camperTip: 'Carrer Llarg, 3. Reserva y paga desde la app TripStop (16 € la noche, máximo 10 noches seguidas).',
    utopiaTip: 'En verano reserva con varios días de antelación. Es la mejor base para recorrer el norte y el Llevant.',
    tags: ['water', 'dump', 'power', { key: 'parking-paid', label: '16 € / noche' }],
    image: '/images/guia/area-son-serra.jpg',
    credit: { author: 'Olaf Tausch', license: 'CC BY 3.0', source: commons('Son Serra de Marina, en Santa Margarita (Baleares, España).jpg') },
  },
  {
    id: 'area-muro',
    name: 'Área de autocaravanas de Muro',
    category: 'dormir',
    area: 'Muro',
    lat: 39.7278, lng: 3.0586,
    summary: 'Área municipal en la avinguda de Sineu, junto a la antigua Escola Graduada, para pasar la noche y hacer servicios.',
    camperTip: 'Gratuita y sin reserva: se ocupa por orden de llegada. Tiene toma de agua potable y vaciado de aguas grises.',
    utopiaTip: 'Llega a media tarde para asegurar plaza. La Platja de Muro está a 15 minutos en camper.',
    tags: ['water', 'dump', { key: 'parking-free', label: 'Gratis' }],
    image: '/images/guia/area-muro.jpg',
    credit: { author: 'Chixoy', license: 'CC BY-SA 3.0', source: commons('Muro, en Mallorca (Baleares, España).jpg') },
  },
  {
    id: 'base-utopia',
    name: 'Base Utopia Van Life',
    category: 'dormir',
    area: 'Son Oms, Palma',
    lat: 39.5359, lng: 2.7356,
    summary: 'Nuestro punto de recogida y devolución, a 5 minutos del aeropuerto.',
    camperTip: 'Para cualquier duda durante el viaje, llámanos o escríbenos por WhatsApp.',
    utopiaTip: 'El vaciado de aguas corre de tu cuenta: hazlo en las áreas de Son Serra de Marina o Muro antes de devolver la camper.',
    tags: ['services'],
    image: '/images/campers/neo/neo-ext.png',
  },
]

export interface GuideRoute {
  id: string
  name: string
  days: string
  summary: string
  spotIds: string[]
}

export const GUIDE_ROUTES: GuideRoute[] = [
  {
    id: 'tramuntana',
    name: 'Serra de Tramuntana',
    days: '2–3 días',
    summary: 'La Ma-10 de sur a norte: miradores sobre el mar, pueblos de piedra y la bajada a Sa Calobra.',
    spotIds: ['coll-sa-gramola', 'mirador-ricardo-roca', 'mirador-ses-animes', 'valldemossa', 'sa-foradada', 'deia', 'port-soller', 'fornalutx', 'santuari-lluc', 'sant-llorenc-escorca', 'sa-calobra'],
  },
  {
    id: 'sur',
    name: 'Calas del sur',
    days: '2 días',
    summary: 'Agua turquesa y playas vírgenes entre Cala Pi y Portocolom. Madruga para aparcar sin agobios.',
    spotIds: ['torre-cala-pi', 'es-trenc', 'far-ses-salines', 'calo-des-moro', 'cala-llombards', 'cala-mondrago', 'portocolom'],
  },
  {
    id: 'norte',
    name: 'Norte y Llevant',
    days: '3 días',
    summary: 'Formentor a primera hora, La Victòria, una noche en Son Serra y las calas salvajes de Artà y Capdepera.',
    spotIds: ['mirador-colomer', 'talaia-albercutx', 'platja-formentor', 'cala-sant-vicenc', 'ermita-victoria', 'alcudia', 'area-son-serra', 'cala-torta', 'cala-mesquida', 'cala-agulla', 'coves-arta'],
  },
]

export interface GuideRule {
  title: string
  body: string
}

export const GUIDE_RULES: GuideRule[] = [
  {
    title: 'Aparcar sí, acampar no',
    body: 'Puedes aparcar la camper donde se permita aparcar cualquier coche y descansar dentro. Se considera acampada sacar toldo, mesas o sillas, poner calzos, abrir ventanas proyectables hacia fuera o verter agua. Fuera de las áreas autorizadas, acampar está prohibido y se multa.',
  },
  {
    title: 'Muchos municipios prohíben pasar la noche',
    body: 'En buena parte de la costa hay ordenanzas y señales que impiden estacionar autocaravanas y campers de noche, sobre todo en verano. Respeta siempre la señalización. Para dormir tranquilo, usa las áreas de Son Serra de Marina o de Muro.',
  },
  {
    title: 'Espacios naturales',
    body: 'En parques naturales y zonas protegidas (Mondragó, Es Trenc, Llevant…) no se puede pernoctar ni circular por caminos de tierra cerrados. Aparca solo en los aparcamientos habilitados.',
  },
  {
    title: 'Formentor en temporada',
    body: 'Del 15 de mayo al 18 de octubre de 2026, la carretera de Formentor (Ma-2210) está cerrada al vehículo privado de 10:00 a 22:00. Entra antes de las 10 o sube en el bus que sale del Port de Pollença.',
  },
  {
    title: 'Aguas grises y negras',
    body: 'El vaciado de los depósitos corre de tu cuenta durante el viaje. Hazlo solo en puntos autorizados, como las áreas de Son Serra de Marina o Muro. Vaciar en la calle, en el campo o en alcantarillas es una infracción grave.',
  },
]

export const GUIDE_TIPS: string[] = [
  'Madruga: las calas más conocidas tienen aparcamientos pequeños y en verano se llenan antes de las 10.',
  'En la Serra de Tramuntana las carreteras son estrechas. Conduce sin prisa, usa marchas cortas en las bajadas y deja pasar a los ciclistas con margen.',
  'No dejes objetos de valor a la vista dentro de la camper cuando la aparques en zonas de playa.',
  'Lleva siempre agua y algo de comida: en muchas calas vírgenes no hay ningún servicio.',
  'Llévate tu basura y deja cada sitio como lo encontraste. Así seguirá habiendo lugares donde las campers son bienvenidas.',
]
